# Site settings
title: Stefano Oliva
email: oliva.stefano@gmail.com
url: https://stefanooliva.github.io
description: "Awesome"
skills: "Pizza"
meta_author: Oliva Stefano

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Stefano Oliva
  location: Stockholm
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ollyste
  - title: linkedin
    url: www.linkedin.com/in/olivastefano
  - title: instagram
    url: www.instagram.com/ollyste

# Postal address (add as many lines as necessary)
address:
  - line: oliva [dot] stefano [at] gmail [dot] com
  - line: 0768686447

# Credits content
credits: 'This is created with <a href="http://startbootstrap.com">Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
